name: CI/CD Pipeline Node.js

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '13'

    - name: Install backend dependencies
      run: npm install

    - name: Build frontend
      working-directory: ./client
      run: |
        npm install
        npm run build

    - name: Deploy to Server via SSH and PM2
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem
        ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /var/www/html/mern-marketplace

          # Reset working directory and pull latest code
          git fetch origin
          git reset --hard origin/main
          git clean -fd

          # Install backend dependencies
          npm install

          # Install frontend dependencies
          cd client
          npm install
          npm run build
          cd ..

          # Install PM2 if not already installed
          if ! command -v pm2 &> /dev/null
          then
            echo "PM2 not found. Installing PM2..."
            sudo npm install -g pm2
          fi

          # Restart or start PM2 process
          pm2 restart mern-marketplace || pm2 start server/server.js --name mern-marketplace
        EOF
        rm -f key.pem
