name: CI/CD Pipeline Node.js

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install backend dependencies
      run: npm install

    - name: Build frontend
      working-directory: ./client
      run: |
        npm install
        npm run build

    - name: Deploy to Server via SSH and PM2
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem
        ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          source "$NVM_DIR/bash_completion"
          nvm use 18 || nvm install 18

          cd /var/www/html/mern-marketplace

          # Reset local changes before pulling
          git fetch origin
          git reset --hard origin/main
          git clean -fd

          npm install
          cd client
          npm install
          npm run build
          cd ..

          # Ensure PM2 is in path
          export PATH="$HOME/.npm-global/bin:$PATH"
          pm2 restart mern-marketplace || pm2 start server/server.js --name mern-marketplace
        EOF
        rm -f key.pem
