name: CI/CD Pipeline Node.js

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js using NVM
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
        nvm install 13.12.0  # Install node 13.12.0 to match package engine version
        nvm use 13.12.0

    - name: Install backend dependencies
      run: npm install

    - name: Build frontend
      working-directory: ./client
      run: |
        # Set environment variable to use OpenSSL legacy support
        export NODE_OPTIONS=--openssl-legacy-provider
        npm install
        npm run build

    - name: Deploy to Server via SSH and PM2
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem
        ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          # Check if node and npm are installed, if not install them
          if ! command -v node &> /dev/null
          then
            echo "Node.js not found. Installing Node.js..."
            curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -
            sudo apt-get install -y nodejs
          fi

          # Check if npm is installed, if not install it
          if ! command -v npm &> /dev/null
          then
            echo "npm not found. Installing npm..."
            sudo apt-get install -y npm
          fi

          # Install backend dependencies
          cd /var/www/html/mern-marketplace
          git fetch origin
          git reset --hard origin/main
          git clean -fd
          npm install

          # Install frontend dependencies
          cd client
          npm install
          npm run build
          cd ..

          # Install PM2 if not already installed
          if ! command -v pm2 &> /dev/null
          then
            echo "PM2 not found. Installing PM2..."
            sudo npm install -g pm2
          fi

          # Restart or start PM2 process
          pm2 restart mern-marketplace || pm2 start server/server.js --name mern-marketplace
        EOF
        rm -f key.pem
